name: Build and Publish Documentation to GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      # Only rebuild documentation when docs have changed
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/publish_mkdocs.yml"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.13
          publish_branch: gh-pages
      - name: Install Dependencies
        run: |
          pip install mkdocs-material mkdocs-jupyter neoteroi-mkdocs mkdocs-awesome-pages-plugin lxml_html_clean

      - name: Deploy Documentation
        run: python -m mkdocs  gh-deploy --force -f mkdocs.yml
